# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: grafana-azure
metadata:
  template: grafana-azure-journey@1.0.0
infra:
  provider: bicep
  path: infra-grafana
  module: main
